Migrate unit tests for Protocols.Connector project
southworks/Agents-for-net pull request #2
Opened 2024-11-20 19:45 UTC by sw-joelmut

## Description
This PR migrates the missing unit tests from _BotBuilder-DotNet_, to cover the _RestUserTokenClient_, _BotSignInRestClient_, _RetryParams_, and _UserTokenRestClient_ classes of **_Microsoft.Agents.Protocols.Connector_** project.

## Detailed Changes
- Added test classes to covert each _RestUserTokenClient_, _BotSignInRestClient_, _RetryParams_, and _UserTokenRestClient_ class.

## Testing
This image shows the new tests passing.
![image](https://github.com/user-attachments/assets/d7a4bd54-28dc-4266-965b-c3366a80b5f9)

2024-11-21 12:06 UTC, ceciliaavila requested changes
Should we use the same type of test name for all the tests we add? 🤔

2024-11-21 12:06 UTC, ceciliaavila commented on src/tests/Microsoft.Agents.Protocol.Connector.Tests/RestUserTokenClientTests.cs
> +                await userToken.GetAadTokensAsync(null, ChannelId, resourceUrls, ChannelId, CancellationToken.None);
```suggestion
                await userToken.GetAadTokensAsync(null, ConnectionName, resourceUrls, ChannelId, CancellationToken.None);
```

2024-11-21 12:06 UTC, ceciliaavila commented on src/tests/Microsoft.Agents.Protocol.Connector.Tests/RestUserTokenClientTests.cs
> +                await userToken.ExchangeTokenAsync(null, ChannelId, ChannelId, tokenExchange, CancellationToken.None);
```suggestion
                await userToken.ExchangeTokenAsync(null, ConnectionName, ChannelId, tokenExchange, CancellationToken.None);
```

2024-11-21 12:06 UTC, ceciliaavila commented on src/tests/Microsoft.Agents.Protocol.Connector.Tests/BotSignInRestClientTests.cs
> +namespace Microsoft.Agents.Protocols.Connector.Tests
Should we use this namespace or the one corresponding to the folder tree: Microsoft.Agents.Connector.Tests?

2024-11-21 12:06 UTC, ceciliaavila commented on src/tests/Microsoft.Agents.Protocol.Connector.Tests/RetryParamsTests.cs
> +            var retryParams = RetryParams.DefaultBackOff(10);
Is this correct? the name of the test says 5 retries.

2024-11-22 13:29 UTC, sw-joelmut commented
Feedback applied, thanks!

2024-11-22 16:46 UTC, ceciliaavila requested changes
One small detail.

2024-11-22 16:46 UTC, ceciliaavila commented on src/tests/Microsoft.Agents.Protocol.Connector.Tests/RestUserTokenClientTests.cs
> +            await Assert.ThrowsAsync<ArgumentNullException>(() => client.GetAadTokensAsync(null, ChannelId, ResourceUrls, ChannelId, CancellationToken.None));
```suggestion
            await Assert.ThrowsAsync<ArgumentNullException>(() => client.GetAadTokensAsync(null, ConnectionName, ResourceUrls, ChannelId, CancellationToken.None));
```

2024-11-26 14:57 UTC, JhontSouth approved these changes

2024-12-20 12:59 UTC, ceciliaavila commented
These changes were sent via .path files

2024-12-20 12:59 UTC, closed without merging